# Generated by Django 5.2.8 on 2025-11-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_alter_hotelimage_hotel_alter_roomimage_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='service',
            field=models.ManyToManyField(to='booking_app.service'),
        ),
    ]
