# Generated by Django 5.2.8 on 2025-11-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_hotel_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_status_en',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_status_ru',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type_en',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type_ru',
        ),
    ]
